### PR TITLE
Compatitbility with persistent-2

### PR DESCRIPTION
**Pull request by mytskine**
I've used this patch for many months in a pet project, but forgot to send a PR. Thanks for your paginator!.

### CODE REVIEW

**Comment by pbrisbin** [comment]
Thanks! I'll merge and bump-release today most likely.

**Comment by cosmo0920** [comment]
:+1:
How long does it take until new version release?

**Comment by pbrisbin** [comment]
I'm sorry, I completely forgot about this PR -- thanks for the bump. I'll try to take care of this a soon as I can.

**Comment by pbrisbin** [comment]
Merged as 9b7ee755

**Comment by pbrisbin** [comment]
Released as 0.10.0

**Comment by cosmo0920** [comment]
Thanks!

**Pull request closed without merging**
